name = "portfolio-timeline"
compatibility_date = "2024-09-23"

pages_build_output_dir = "dist"

[vars]
VITE_TIMELINE_DATA_URL = "https://raw.githubusercontent.com/vigneshdemitro/portfolio-data/main/timeline.json"
