name = "portfolio-timeline"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[vars]
TIMELINE_DATA_URL = "https://raw.githubusercontent.com/vigneshdemitro/portfolio-data/main/timeline.json"